### ISSUE TITLE
[FE] Create the FAQ Section

### ISSUE THREAD

**Issue by edichoska** [learnhubmkd/app#78]
**Task:**
- Implement the FAQ Section as shown in the Figma file: https://www.figma.com/file/zhRSxKmdeXlsdStdL6NdgU/Untitled?type=design&node-id=0-1&mode=design&t=VgX6o5TWVv38P8ns-0
- First you can create an Accordion Component that would be reused. Use Typescript.
- You can use lorem ipsum for the answers text
(at this phase do not worry about responsiveness)

**Comment by RevanchistX** [comment]
@edichoska @stoimenov95 @GregoriBavaro 
I had this idea that should easy to implement.
Every time I see a FAQ on any site, it's only text.

What if we have voice recorded messages that match the written text?
For example: 
- one voice asks the question
- one voice answers the question

Then when the user presses the play button, the text of the FAQ reinitializes with an effect to match the spoken words of the audio. 

Leaving video for inspiration.
https://www.youtube.com/watch?v=W5oawMJaXbU

**Comment by edichoska** [comment]
> @edichoska @stoimenov95 @GregoriBavaro I had this idea that should easy to implement. Every time I see a FAQ on any site, it's only text.
> 
> What if we have voice recorded messages that match the written text? For example:
> 
> * one voice asks the question
> * one voice answers the question
> 
> Then when the user presses the play button, the text of the FAQ reinitializes with an effect to match the spoken words of the audio.
> 
> Leaving video for inspiration. https://www.youtube.com/watch?v=W5oawMJaXbU

love this! Very cool idea. @GregoriBavaro  look into this

**Comment by RevanchistX** [comment]
Which aspect is not user-friendly?

FAQ's are way too often verbose and if not done right, they end up creating more questions than answers for the user.
This is why I think it will benefit the user:
- Animation: simple fade-in for each word in rhythm of the audio.
> The youtube link is for inspiration/how to approach the problem.
- Audio: gives the user context and lets them absorb the information of the component while enhancing the reading experience.


Additionally:
-I have a ready implementation with GoogleTTS if we wanna automate the text -> audio.
> Obviously, any other tool can be used, this was the pre-AI boom, so 11-labs and other AI powered audio software wasn't available then.
- Alternatively, we need two people to voice act.

**Comment by GregoriBavaro** [comment]
Hello team,

Thank you Viktor for proposing the implementation of a Text-to-Speech feature for our website's FAQ section. Upon initial consideration, the concept appears intriguing and potentially beneficial. However,
I find myself contemplating its practical advantages from a consumer standpoint. It's essential to ensure that any additional feature enhances the user experience and facilitates the accessibility of information.
While the integration of Text-to-Speech functionality could notably assist individuals with visual impairments, it prompts us to carefully assess its broader impact on our platform. Implementing such a feature
necessitates ensuring uniform accessibility across all components, thereby warranting meticulous attention to detail and potential resource allocation.

From a developer's perspective, I am certainly inclined towards exploring innovative enhancements for our platform, embracing next-generation UI/UX concepts. However, as a client,
I perceive the primary value lies in simplicity and functionality rather than solely aesthetic appeal. It's imperative to acknowledge that individual perspectives may vary,
and while some may perceive this feature as a significant asset, others may prioritize different aspects of usability.

Therefore, I propose further discussion and evaluation to ascertain the optimal balance between innovation and practicality in our website's enhancement endeavors.

**Comment by RevanchistX** [comment]
@GregoriBavaro I might have mislead you with the TTS functionality.
I wanted to generate the audio files with the TTS functionality, which would then just be played by the regular in-browser player.
This can theoretically be done on the fly, but we'll discuss implementation details if we decide to go this approach.

I agree with you, making the whole site TTS-able is another can of worms.
However, I do think that only having the FAQ section be done like this helps with bringing the user and the creator closer, since it's meant to embody the interaction between the two entities. 
- It will give the user end perspective, context
- It will save Davor from repeating the answers all the time because he can just link the audio File. hahah

**Comment by stoimenov95** [comment]
@RevanchistX @edichoska @GregoriBavaro 
Hey guys, while the idea sounds great and interesting, we should also consult the UI/UX team about it.
My subjective point of view is that I don't like sounds/speech on web apps, and I am worried this feature will differ a lot from the rest of the website.
